# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[('男', 0), ('女', 1)], default=0, verbose_name='性别')),
            ],
            options={
                'verbose_name_plural': '任务',
                'db_table': 't_bd_task',
            },
        ),
    ]
